global class RealTimeMetalQuotesParser {
    
    public Decimal Spread {get; set;}
    public Decimal Ask {get; set;}
    public Decimal Mid {get; set;}
    public Decimal Bid {get; set;}
    public Decimal Delay {get; set;}
    public String Outcome {get; set;}
    public String Source {get; set;}
    public String Time_x {get; set;}
    public String Date_x {get; set;}
    public String Currency_x {get; set;}
    public String QuoteType {get; set;}
    public String Unit {get; set;}
    public String Symbol {get; set;}
    public String Name {get; set;}
    public String Identity {get; set;}
    public String Message {get; set;}

}